items:
  ARCHEAN_aileron.Aileron:
    max_stack: 256

recipes:
  - label: Aileron
    context: crafter
    category: components
    time: 10
    input:
      ARCHEAN_parts.Casing: 1
      ARCHEAN_parts.Screw: 100
      ARCHEAN_parts.Connector: 1
      ARCHEAN_celestial.Aluminium: 9000
    output:
      ARCHEAN_aileron.Aileron: 1
