items:
  ARCHEAN_avatar.Canister:
    max_stack: 256
  ARCHEAN_avatar.PilotSeat:
    max_stack: 64
  ARCHEAN_avatar.Bobblehead:
    max_stack: 256


inventory_creative_backpack:
  - ARCHEAN_hid.ToggleButton
  - ARCHEAN_hid.PushButton
  - ARCHEAN_hid.ThrottleLever
  - ARCHEAN_hid.Numpad
  - ARCHEAN_hid.Keyboard
  - ARCHEAN_avatar.PilotSeat
  - ARCHEAN_computer.Computer
  - ARCHEAN_computer.MiniComputer
  - ARCHEAN_ownership.OwnerPad
  
  - ARCHEAN_wheel.Wheel
  - ARCHEAN_wheel.SmallWheel
  - ARCHEAN_build.SmallPivot
  - ARCHEAN_build.SmallHinge
  - ARCHEAN_build.LinearTrack
  - ARCHEAN_build.Hitch
  - ARCHEAN_anchor.GroundAnchor
  - ARCHEAN_avatar.Bobblehead
  - ARCHEAN_misc.Step
  
  - ARCHEAN_celestial.SolarPanel
  - ARCHEAN_battery.LowVoltageBattery
  - ARCHEAN_junction.DataJunction
  - ARCHEAN_junction.LowVoltageJunction
  - ARCHEAN_junction.LowVoltageRelay
  - ARCHEAN_junction.DataBridge
  - ARCHEAN_junction.LowVoltageBridge
  - ARCHEAN_light.SpotLight
  - ARCHEAN_light.Lamp
  
  - ARCHEAN_celestial.SolarSensor
  - ARCHEAN_sensor1.AltitudeSensor
  - ARCHEAN_sensor1.SpeedSensor
  - ARCHEAN_sensor1.DensitySensor
  - ARCHEAN_sensor1.TemperatureSensor
  - ARCHEAN_sensor1.TiltSensor
  - ARCHEAN_sensor1.LinearVelocitySensor
  - ARCHEAN_sensor1.AngularVelocitySensor
  - ARCHEAN_sensor1.VehiclePhysicsSensor
  
  - ARCHEAN_celestial.MiningDrill
  - ARCHEAN_storage.SmallContainer
  - ARCHEAN_celestial.OreScanner
  - ARCHEAN_celestial.TerrainScanner
  - ARCHEAN_beacon.Beacon
  - ARCHEAN_beep.Buzzer
  - ARCHEAN_storage.TrashCan
  - ARCHEAN_build.PaintTool
  - ARCHEAN_build.LabelTool
  
##########

  - ARCHEAN_battery.HighVoltageBattery
  - ARCHEAN_wheel.BigWheel
  - ARCHEAN_propeller.Propeller
  - ARCHEAN_thruster.MiniThruster
  - ARCHEAN_thruster.SmallThruster
  - ARCHEAN_thruster.BigThruster
  - ARCHEAN_rcs.RCS
  - ARCHEAN_celestial.GeothermalExchanger
  - ARCHEAN_nuclear.FissionReactor

  - ARCHEAN_build.HighVoltageCable
  - ARCHEAN_build.FluidPipe
  - ARCHEAN_build.ItemConduit
  - ARCHEAN_build.BlueprintTool
  - ARCHEAN_build.DashboardTool
  - ARCHEAN_build.Volume
  - ARCHEAN_machines.ItemConveyor
  - ARCHEAN_machines.Crusher
  - ARCHEAN_storage.Container
  
  - ARCHEAN_celestial.NavInstrument
  - ARCHEAN_aileron.Aileron
  - ARCHEAN_computer.Router
  - ARCHEAN_computer.MiniRouter
  - ARCHEAN_hud.HudController
  - ARCHEAN_machines.Crafter
  - ARCHEAN_build.DockableDoor
  - ARCHEAN_build.DockingPort
  - ARCHEAN_rtg.RTG
  
  - ARCHEAN_tank.SmallFluidTank
  - ARCHEAN_tank.FluidTank
  - ARCHEAN_tank.BigFluidTank
  - ARCHEAN_thruster.FluidPump
  - ARCHEAN_thruster.SmallTurboPump
  - ARCHEAN_thruster.BigTurboPump
  - ARCHEAN_chemical.FluidPort
  - ARCHEAN_junction.FluidValve
  - ARCHEAN_chemical.Electrolyser
  
  - ARCHEAN_chemical.SabatierReactor
  - ARCHEAN_chemical.EnrichmentCentrifuge
  - ARCHEAN_chemical.ChemicalFurnace
  - ARCHEAN_gyroscope.SmallGyroscope
  - ARCHEAN_gyroscope.Gyroscope
  - ARCHEAN_machines.PassiveRadiator
  - ARCHEAN_machines.ActiveRadiator
  - ARCHEAN_machines.SmallSteamTurbine
  - ARCHEAN_machines.SteamTurbine
  
  - ARCHEAN_junction.FluidJunction
  - ARCHEAN_junction.HighVoltageJunction
  - ARCHEAN_junction.ItemJunction
  - ARCHEAN_junction.HighVoltageRelay
  - ARCHEAN_junction.PowerConverter
  - ARCHEAN_junction.HighVoltageBridge
  - ARCHEAN_junction.FluidBridge
  - ARCHEAN_junction.ItemBridge
# - 

inventory_creative_belt:
  - ARCHEAN_build.ConstructorTool
  - ARCHEAN_build.DestructorTool
  - ARCHEAN_build.DataCable
  - ARCHEAN_build.LowVoltageCable

recipes:

  - label: PilotSeat
    context: crafter
    category: components
    time: 30
    input:
      ARCHEAN_parts.Casing: 40
      ARCHEAN_parts.Plastic: 40
      ARCHEAN_parts.Connector: 1
    output:
      ARCHEAN_avatar.PilotSeat: 1

  - label: Bobblehead
    context: crafter
    category: components
    time: 5
    input:
      ARCHEAN_parts.Casing: 1
      ARCHEAN_parts.Plastic: 1
      ARCHEAN_parts.Screw: 10
    output:
      ARCHEAN_avatar.Bobblehead: 1

  - label: Canister
    context: crafter
    category: misc
    time: 1
    input:
      ARCHEAN_parts.Plastic: 4
    output:
      ARCHEAN_avatar.Canister: 1
