items:
  ARCHEAN_beacon.Beacon:
    max_stack: 256

recipes:
  - label: Beacon
    context: crafter
    category: components
    time: 30
    input:
      ARCHEAN_parts.Circuit: 1
      ARCHEAN_parts.Casing: 1
      ARCHEAN_parts.Magnet: 1
      ARCHEAN_parts.Capacitor: 1
      ARCHEAN_parts.Connector: 2
    output:
      ARCHEAN_beacon.Beacon: 1
