items:
  ARCHEAN_junction.FluidJunction:
    max_stack: 256
  ARCHEAN_junction.DataJunction:
    max_stack: 256
  ARCHEAN_junction.LowVoltageJunction:
    max_stack: 256
  ARCHEAN_junction.HighVoltageJunction:
    max_stack: 256
  ARCHEAN_junction.ItemJunction:
    max_stack: 256
  ARCHEAN_junction.LowVoltageRelay:
    max_stack: 256
  ARCHEAN_junction.HighVoltageRelay:
    max_stack: 256
  ARCHEAN_junction.PowerConverter:
    max_stack: 256
  ARCHEAN_junction.DataBridge:
    max_stack: 256
  ARCHEAN_junction.LowVoltageBridge:
    max_stack: 256
  ARCHEAN_junction.HighVoltageBridge:
    max_stack: 256
  ARCHEAN_junction.FluidBridge:
    max_stack: 256
  ARCHEAN_junction.ItemBridge:
    max_stack: 256
  ARCHEAN_junction.FluidValve:
    max_stack: 256


recipes:

  - label: FluidJunction
    context: crafter
    category: components
    time: 1
    input:
      ARCHEAN_parts.Casing: 20
      ARCHEAN_parts.Connector: 5
    output:
      ARCHEAN_junction.FluidJunction: 1
  
  - label: DataJunction
    context: crafter
    category: components
    time: 1
    input:
      ARCHEAN_parts.Casing: 1
      ARCHEAN_parts.Connector: 5
    output:
      ARCHEAN_junction.DataJunction: 1
  
  - label: LowVoltageJunction
    context: crafter
    category: components
    time: 1
    input:
      ARCHEAN_parts.Casing: 1
      ARCHEAN_parts.Connector: 5
    output:
      ARCHEAN_junction.LowVoltageJunction: 1
  
  - label: HighVoltageJunction
    context: crafter
    category: components
    time: 1
    input:
      ARCHEAN_parts.Casing: 1
      ARCHEAN_parts.Connector: 5
    output:
      ARCHEAN_junction.HighVoltageJunction: 1
  
  - label: ItemJunction
    context: crafter
    category: components
    time: 1
    input:
      ARCHEAN_parts.Casing: 20
      ARCHEAN_parts.Connector: 5
    output:
      ARCHEAN_junction.ItemJunction: 1
  
  - label: LowVoltageRelay
    context: crafter
    category: components
    time: 1
    input:
      ARCHEAN_parts.Casing: 1
      ARCHEAN_parts.Connector: 3
    output:
      ARCHEAN_junction.LowVoltageRelay: 1
  
  - label: HighVoltageRelay
    context: crafter
    category: components
    time: 1
    input:
      ARCHEAN_parts.Casing: 1
      ARCHEAN_parts.Connector: 3
    output:
      ARCHEAN_junction.HighVoltageRelay: 1
  
  - label: PowerConverter
    context: crafter
    category: components
    time: 10
    input:
      ARCHEAN_parts.Casing: 4
      ARCHEAN_parts.Connector: 2
      ARCHEAN_parts.Circuit: 1
      ARCHEAN_parts.Magnet: 1
    output:
      ARCHEAN_junction.PowerConverter: 1
  
  - label: DataBridge
    context: crafter
    category: components
    time: 1
    input:
      ARCHEAN_parts.Casing: 1
      ARCHEAN_parts.Connector: 2
    output:
      ARCHEAN_junction.DataBridge: 1
  
  - label: LowVoltageBridge
    context: crafter
    category: components
    time: 1
    input:
      ARCHEAN_parts.Casing: 1
      ARCHEAN_parts.Connector: 2
    output:
      ARCHEAN_junction.LowVoltageBridge: 1
  
  - label: HighVoltageBridge
    context: crafter
    category: components
    time: 1
    input:
      ARCHEAN_parts.Casing: 1
      ARCHEAN_parts.Connector: 2
    output:
      ARCHEAN_junction.HighVoltageBridge: 1
  
  - label: FluidBridge
    context: crafter
    category: components
    time: 1
    input:
      ARCHEAN_parts.Casing: 1
      ARCHEAN_parts.Connector: 2
    output:
      ARCHEAN_junction.FluidBridge: 1

  - label: ItemBridge
    context: crafter
    category: components
    time: 1
    input:
      ARCHEAN_parts.Casing: 1
      ARCHEAN_parts.Connector: 2
    output:
      ARCHEAN_junction.ItemBridge: 1

  - label: FluidValve
    context: crafter
    category: components
    time: 1
    input:
      ARCHEAN_parts.Casing: 1
      ARCHEAN_parts.Connector: 3
    output:
      ARCHEAN_junction.FluidValve: 1
