// DO NOT EDIT THIS FILE
/* 
	MODDING GUIDE (C/C++)

	1. Get yourself an official VENDOR name on the official website
	
	2. Come up with a name for your mod that is all lowercase with a maximum of 12 alphanumeric characters, starting with a letter
	
	For the following, replace words in square brackets [] with your information without the brackets

	4. Create a directory [path_to_game]/modules/[MYVENDOR]_[mymod]/

	5. Create a file [mymod].c in that directory that will contain the source code for your mod
	
		Example source code in [mymod].c:
			
			#include "../ARCHEAN_Mod.h" // add this exact line once at the very beginning of your source code
			
			ARCHEAN_FUNCTION( Load ) {
				// this code will be executed when your mod is loaded
			}
			
			ARCHEAN_FUNCTION( Unload ) {
				// this code will be executed when your mod is unloaded
			}
			
			//... more functions defined in documentation

	6. Compile your mod with the following command: gcc -shared -o [MYVENDOR]_[mymod].ARCHEAN_Mod.[dll|so] [mymod].c
	
	7. Add [MYVENDOR]_[mymod] to the list of enabled mods in Archean-data/mods.txt
	
	8. Enjoy your mod!
*/

#ifndef _ARCHEAN_MOD_H
#define _ARCHEAN_MOD_H

#define ARCHEAN_MOD_VERSION 0

#ifdef XENON_GAME // Only defined within the game's source code. Do NOT define XENON_GAME in your mod.
	#include "ARCHEAN_Mod.hh"
#else
	#define ARCHEAN_MOD_DEFINE(...) 
	#ifdef __cplusplus
		extern "C" int _ARCHEAN_Mod_VERSION() {return ARCHEAN_MOD_VERSION;}
		#define ARCHEAN_FUNCTION(F) extern "C" void F (struct F ## _PARAMS * Params_)
	#else
		int _ARCHEAN_Mod_VERSION() {return ARCHEAN_MOD_VERSION;}
		#define ARCHEAN_FUNCTION(F) void F (struct F ## _PARAMS * Params_)
	#endif
	#define PARAM (*Params_)
#endif

///////////////////////////////////////////////////////////////////////////////////////////////////////


struct Load_PARAMS {
};

struct Unload_PARAMS {
};


ARCHEAN_MOD_DEFINE(Load,Unload
)


#endif
