cv2pdb.exe Archean.exe
cv2pdb.exe console.exe
cv2pdb.exe game.dll
cv2pdb.exe server.dll
cv2pdb.exe client.dll
cv2pdb.exe XenonAudio.dll
cv2pdb.exe XenonCpu.dll
cv2pdb.exe XenonEngine.dll
cv2pdb.exe XenonFileSystem.dll
cv2pdb.exe XenonGraphics.dll
cv2pdb.exe XenonModular.dll
cv2pdb.exe XenonNet.dll
cv2pdb.exe XenonRenderer.dll
cv2pdb.exe XenonVk.dll
cv2pdb.exe modules/ARCHEAN_build/ARCHEAN_build.SERVER_Mod.dll
cv2pdb.exe modules/ARCHEAN_build/ARCHEAN_build.GAME_Mod.dll
cv2pdb.exe modules/ARCHEAN_rays/ARCHEAN_rays.GAME_Mod.dll
cv2pdb.exe modules/ARCHEAN_avatar/ARCHEAN_avatar.GAME_Mod.dll
cv2pdb.exe modules/ARCHEAN_avatar/ARCHEAN_avatar.SERVER_Mod.dll
