items:
  ARCHEAN_ownership.OwnerPad:
    max_stack: 256

recipes:

  - label: OwnerPad
    context: crafter
    category: components
    time: 10
    input:
      ARCHEAN_parts.Circuit: 1
      ARCHEAN_parts.Panel: 1
      ARCHEAN_parts.LED: 10
    output:
      ARCHEAN_ownership.OwnerPad: 1
