components:
  - ARCHEAN_battery.LowVoltageBattery
  - ARCHEAN_battery.HighVoltageBattery

recipes:
  
  - label: LowVoltageBattery
    context: crafter
    category: components
    time: 10
    input:
      ARCHEAN_parts.Casing: 1
      ARCHEAN_celestial.Iron: 100
      ARCHEAN_parts.Screw: 10
      ARCHEAN_parts.Circuit: 1
      ARCHEAN_parts.Capacitor: 40
      ARCHEAN_parts.Connector: 5
    output:
      ARCHEAN_battery.LowVoltageBattery: 1
  
  - label: HighVoltageBattery
    context: crafter
    category: components
    time: 20
    input:
      ARCHEAN_parts.Casing: 1
      ARCHEAN_celestial.Iron: 1000
      ARCHEAN_parts.Screw: 100
      ARCHEAN_parts.Circuit: 1
      ARCHEAN_parts.Capacitor: 400
      ARCHEAN_parts.Connector: 5
    output:
      ARCHEAN_battery.HighVoltageBattery: 1
