items:
  ARCHEAN_battery.LowVoltageBattery:
    max_stack: 256
  ARCHEAN_battery.HighVoltageBattery:
    max_stack: 64

recipes:
  
  - label: LowVoltageBattery
    context: crafter
    category: components
    time: 10
    input:
      ARCHEAN_parts.Casing: 1
      ARCHEAN_parts.Circuit: 1
      ARCHEAN_parts.Capacitor: 90
      ARCHEAN_parts.Connector: 5
    output:
      ARCHEAN_battery.LowVoltageBattery: 1
  
  - label: HighVoltageBattery
    context: crafter
    category: components
    time: 20
    input:
      ARCHEAN_parts.Casing: 10
      ARCHEAN_parts.Circuit: 1
      ARCHEAN_parts.Capacitor: 900
      ARCHEAN_parts.Connector: 5
    output:
      ARCHEAN_battery.HighVoltageBattery: 1
