parts:
  - ARCHEAN_parts.Screw
  - ARCHEAN_parts.Plastic
  - ARCHEAN_parts.Wire
  - ARCHEAN_parts.Connector
  - ARCHEAN_parts.Magnet
  - ARCHEAN_parts.Diode
  - ARCHEAN_parts.Capacitor
  - ARCHEAN_parts.Panel
  - ARCHEAN_parts.Disk
  - ARCHEAN_parts.Casing
  - ARCHEAN_parts.Circuit
  - ARCHEAN_parts.Motor
  - ARCHEAN_parts.LED

recipes:

  - label: Screw
    context: avatar
    category: parts
    time: 0.1
    input:
      ARCHEAN_celestial.Iron: 1
    output:
      ARCHEAN_parts.Screw: 1

  - label: Plastic
    context: avatar
    category: parts
    time: 0.1
    input:
      ARCHEAN_celestial.Carbon: 1
      ARCHEAN_celestial.Silicon: 1
      o2: 0.001
      h2: 0.001
    output:
      ARCHEAN_parts.Plastic: 1
  
  - label: Wire
    context: avatar
    category: parts
    time: 0.1
    input:
      ARCHEAN_celestial.Copper: 1
      ARCHEAN_parts.Plastic: 1
    output:
      ARCHEAN_parts.Wire: 1
    
  - label: Connector
    context: avatar
    category: parts
    time: 1
    input:
      ARCHEAN_parts.Wire: 1
      ARCHEAN_parts.Plastic: 1
      ARCHEAN_celestial.Iron: 1
    output:
      ARCHEAN_parts.Connector: 1
  
  - label: Magnet
    context: avatar
    category: parts
    time: 5
    input:
      ARCHEAN_celestial.Iron: 100
    output:
      ARCHEAN_parts.Magnet: 1
  
  - label: Diode
    context: avatar
    category: parts
    time: 1
    input:
      ARCHEAN_celestial.Silicon: 1
      ARCHEAN_celestial.Iron: 1
      ARCHEAN_parts.Wire: 1
      ARCHEAN_parts.Plastic: 1
    output:
      ARCHEAN_parts.Diode: 1
  
  - label: Capacitor
    context: avatar
    category: parts
    time: 1
    input:
      ARCHEAN_celestial.Iron: 1
      ARCHEAN_celestial.Silicon: 1
      ARCHEAN_parts.Wire: 1
      ARCHEAN_celestial.Carbon: 1
    output:
      ARCHEAN_parts.Capacitor: 1
  
  - label: Panel
    context: avatar
    category: parts
    time: 1
    input:
      ARCHEAN_celestial.Iron: 10
    output:
      ARCHEAN_parts.Panel: 1
  
  - label: Disk
    context: avatar
    category: parts
    time: 1
    input:
      ARCHEAN_celestial.Iron: 10
    output:
      ARCHEAN_parts.Disk: 1
  
  - label: Casing
    context: avatar
    category: parts
    time: 5
    input:
      ARCHEAN_celestial.Iron: 100
    output:
      ARCHEAN_parts.Casing: 1
  
  - label: Circuit
    context: avatar
    category: parts
    time: 10
    input:
      ARCHEAN_parts.Diode: 10
      ARCHEAN_parts.Capacitor: 10
      ARCHEAN_parts.Wire: 10
      ARCHEAN_parts.Plastic: 1
      ARCHEAN_parts.Panel: 1
      ARCHEAN_celestial.Silicon: 100
    output:
      ARCHEAN_parts.Circuit: 1

  - label: Motor
    context: avatar
    category: parts
    time: 10
    input:
      ARCHEAN_parts.Circuit: 1
      ARCHEAN_parts.Magnet: 10
      ARCHEAN_parts.Wire: 100
      ARCHEAN_parts.Disk: 1
      ARCHEAN_parts.Casing: 1
      ARCHEAN_parts.Connector: 1
    output:
      ARCHEAN_parts.Motor: 1

  - label: LED
    context: avatar
    category: parts
    time: 1
    input:
      ARCHEAN_parts.Wire: 1
      ARCHEAN_parts.Diode: 1
    output:
      ARCHEAN_parts.LED: 1
