components:
  - ARCHEAN_sensor.AltitudeSensor
  - ARCHEAN_sensor.SpeedSensor
  - ARCHEAN_sensor.TiltSensor

recipes:
  
  - label: AltitudeSensor
    context: crafter
    category: components
    time: 1
    input:
      ARCHEAN_parts.Casing: 1
      ARCHEAN_parts.Connector: 1
      ARCHEAN_parts.Circuit: 1
      ARCHEAN_parts.Magnet: 1
    output:
      ARCHEAN_sensor.AltitudeSensor: 1
  
  - label: SpeedSensor
    context: crafter
    category: components
    time: 1
    input:
      ARCHEAN_parts.Casing: 1
      ARCHEAN_parts.Connector: 1
      ARCHEAN_parts.Circuit: 1
      ARCHEAN_parts.Magnet: 1
    output:
      ARCHEAN_sensor.SpeedSensor: 1
  
  - label: TiltSensor
    context: crafter
    category: components
    time: 1
    input:
      ARCHEAN_parts.Casing: 1
      ARCHEAN_parts.Connector: 1
      ARCHEAN_parts.Circuit: 1
      ARCHEAN_parts.Magnet: 1
    output:
      ARCHEAN_sensor.TiltSensor: 1

  - label: LinearVelocitySensor
    context: crafter
    category: components
    time: 1
    input:
      ARCHEAN_parts.Casing: 1
      ARCHEAN_parts.Connector: 1
      ARCHEAN_parts.Circuit: 1
      ARCHEAN_parts.Magnet: 1
    output:
      ARCHEAN_sensor.LinearVelocitySensor: 1

  - label: AngularVelocitySensor
    context: crafter
    category: components
    time: 1
    input:
      ARCHEAN_parts.Casing: 1
      ARCHEAN_parts.Connector: 1
      ARCHEAN_parts.Circuit: 1
      ARCHEAN_parts.Magnet: 1
    output:
      ARCHEAN_sensor.AngularVelocitySensor: 1

  - label: VehiclePhysicsSensor
    context: crafter
    category: components
    time: 1
    input:
      ARCHEAN_parts.Casing: 1
      ARCHEAN_parts.Connector: 1
      ARCHEAN_parts.Circuit: 1
      ARCHEAN_parts.Magnet: 1
    output:
      ARCHEAN_sensor.VehiclePhysicsSensor: 1
