items:
  ARCHEAN_tank.SmallFluidTank:
    max_stack: 256
  ARCHEAN_tank.FluidTank:
    max_stack: 64
  ARCHEAN_tank.BigFluidTank:
    max_stack: 8

recipes:

  - label: SmallFluidTank
    context: crafter
    category: components
    time: 10
    input:
      ARCHEAN_parts.Casing: 1
      ARCHEAN_parts.Connector: 2
      ARCHEAN_celestial.Aluminium: 30000
    output:
      ARCHEAN_tank.SmallFluidTank: 1
    
  - label: FluidTank
    context: crafter
    category: components
    time: 20
    input:
      ARCHEAN_parts.Casing: 1
      ARCHEAN_parts.Connector: 2
      ARCHEAN_celestial.Aluminium: 200000
    output:
      ARCHEAN_tank.FluidTank: 1
  
  - label: BigFluidTank
    context: crafter
    category: components
    time: 30
    input:
      ARCHEAN_parts.Casing: 1
      ARCHEAN_parts.Connector: 2
      ARCHEAN_celestial.Aluminium: 1000000
    output:
      ARCHEAN_tank.BigFluidTank: 1
