items:
  ARCHEAN_celestial.Aluminium:
    max_stack: 10000000
  ARCHEAN_celestial.Chrome:
    max_stack: 10000000
  ARCHEAN_celestial.Copper:
    max_stack: 10000000
  ARCHEAN_celestial.Gold:
    max_stack: 10000000
  ARCHEAN_celestial.Iron:
    max_stack: 10000000
  ARCHEAN_celestial.Lead:
    max_stack: 10000000
  ARCHEAN_celestial.Nickel:
    max_stack: 10000000
  ARCHEAN_celestial.Silicon:
    max_stack: 10000000
  ARCHEAN_celestial.Silver:
    max_stack: 10000000
  ARCHEAN_celestial.Tin:
    max_stack: 10000000
  ARCHEAN_celestial.Titanium:
    max_stack: 10000000
  ARCHEAN_celestial.Tungsten:
    max_stack: 10000000
  ARCHEAN_celestial.Uranium:
    max_stack: 10000000
  ARCHEAN_celestial.Carbon:
    max_stack: 10000000
  ARCHEAN_celestial.Sulfur:
    max_stack: 10000000
  ARCHEAN_celestial.Fluorite:
    max_stack: 10000000

  ARCHEAN_celestial.Rock:
    max_stack: 10000

  ARCHEAN_celestial.RockRakeTool:
    max_stack: 1

  ARCHEAN_celestial.NavInstrument:
    max_stack: 256
  ARCHEAN_celestial.SolarPanel:
    max_stack: 256
  ARCHEAN_celestial.SolarSensor:
    max_stack: 256
  ARCHEAN_celestial.MiningDrill:
    max_stack: 8
  ARCHEAN_celestial.OreScanner:
    max_stack: 256
  ARCHEAN_celestial.TerrainScanner:
    max_stack: 256
  ARCHEAN_celestial.GeothermalExchanger:
    max_stack: 64

recipes:

  - context: crusher
    time: 0.01
    input: ARCHEAN_celestial.Rock
    output:
      ARCHEAN_celestial.Aluminium: input.composition.Al
      ARCHEAN_celestial.Chrome: input.composition.Cr
      ARCHEAN_celestial.Copper: input.composition.Cu
      ARCHEAN_celestial.Gold: input.composition.Au
      ARCHEAN_celestial.Iron: input.composition.Fe
      ARCHEAN_celestial.Lead: input.composition.Pb
      ARCHEAN_celestial.Nickel: input.composition.Ni
      ARCHEAN_celestial.Silicon: input.composition.Si
      ARCHEAN_celestial.Silver: input.composition.Ag
      ARCHEAN_celestial.Tin: input.composition.Sn
      ARCHEAN_celestial.Titanium: input.composition.Ti
      ARCHEAN_celestial.Tungsten: input.composition.W
      ARCHEAN_celestial.Uranium: input.composition.U
      ARCHEAN_celestial.Carbon: input.composition.C
      ARCHEAN_celestial.Sulfur: input.composition.S
      ARCHEAN_celestial.Fluorite: input.composition.F
      ARCHEAN_celestial.Cheese: input.composition.Ch
  
  - label: RockRakeTool
    context: crafter
    category: tools
    time: 10
    input:
      ARCHEAN_celestial.Iron: 1000
    output:
      ARCHEAN_celestial.RockRakeTool: 1
  
  - label: NavInstrument
    context: crafter
    category: components
    time: 30
    input:
      ARCHEAN_parts.Circuit: 1
      ARCHEAN_parts.Casing: 9
      ARCHEAN_parts.LED: 100
      ARCHEAN_parts.Magnet: 1
      ARCHEAN_parts.Capacitor: 1
      ARCHEAN_celestial.Gold: 100
      ARCHEAN_parts.Connector: 2
    output:
      ARCHEAN_celestial.NavInstrument: 1
  
  - label: SolarPanel
    context: crafter
    category: components
    time: 10
    input:
      ARCHEAN_parts.Panel: 10
      ARCHEAN_parts.Connector: 3
      ARCHEAN_celestial.Silicon: 15000
    output:
      ARCHEAN_celestial.SolarPanel: 1
  
  - label: SolarSensor
    context: crafter
    category: components
    time: 10
    input:
      ARCHEAN_parts.Casing: 1
      ARCHEAN_parts.Connector: 1
      ARCHEAN_parts.Diode: 10
    output:
      ARCHEAN_celestial.SolarSensor: 1
  
  - label: MiningDrill
    context: crafter
    category: components
    time: 10
    input:
      ARCHEAN_parts.Casing: 380
      ARCHEAN_parts.Screw: 100
      ARCHEAN_parts.Connector: 3
      ARCHEAN_parts.Motor: 2
      ARCHEAN_celestial.Tungsten: 1000
    output:
      ARCHEAN_celestial.MiningDrill: 1
  
  - label: OreScanner
    context: crafter
    category: components
    time: 10
    input:
      ARCHEAN_parts.Casing: 4
      ARCHEAN_parts.Screw: 100
      ARCHEAN_parts.Connector: 2
      ARCHEAN_parts.Magnet: 1
      ARCHEAN_parts.Circuit: 1
    output:
      ARCHEAN_celestial.OreScanner: 1
  
  - label: TerrainScanner
    context: crafter
    category: components
    time: 10
    input:
      ARCHEAN_parts.Casing: 4
      ARCHEAN_parts.Screw: 100
      ARCHEAN_parts.Connector: 2
      ARCHEAN_parts.Magnet: 1
      ARCHEAN_parts.Circuit: 1
    output:
      ARCHEAN_celestial.TerrainScanner: 1

  - label: GeothermalExchanger
    context: crafter
    category: components
    time: 10
    input:
      ARCHEAN_parts.Casing: 160
      ARCHEAN_parts.Screw: 100
      ARCHEAN_parts.Connector: 4
      ARCHEAN_parts.Motor: 2
      ARCHEAN_celestial.Iron: 20000
    output:
      ARCHEAN_celestial.GeothermalExchanger: 1
  