items:
  ARCHEAN_thruster.MiniThruster:
    max_stack: 256
  ARCHEAN_thruster.SmallThruster:
    max_stack: 256
  ARCHEAN_thruster.BigThruster:
    max_stack: 8
  ARCHEAN_thruster.FluidPump:
    max_stack: 256
  ARCHEAN_thruster.SmallTurboPump:
    max_stack: 256
  ARCHEAN_thruster.BigTurboPump:
    max_stack: 64

recipes:

  - label: MiniThruster
    context: crafter
    category: components
    time: 5
    input:
      ARCHEAN_parts.Casing: 1
      ARCHEAN_parts.Connector: 3
      ARCHEAN_celestial.Iron: 5000
      ARCHEAN_celestial.Aluminium: 5000
    output:
      ARCHEAN_thruster.MiniThruster: 1
  
  - label: SmallThruster
    context: crafter
    category: components
    time: 10
    input:
      ARCHEAN_parts.Casing: 1
      ARCHEAN_parts.Screw: 100
      ARCHEAN_parts.Connector: 4
      ARCHEAN_celestial.Aluminium: 40000
      ARCHEAN_celestial.Titanium: 10000
    output:
      ARCHEAN_thruster.SmallThruster: 1
  
  - label: BigThruster
    context: crafter
    category: components
    time: 20
    input:
      ARCHEAN_parts.Casing: 1
      ARCHEAN_parts.Screw: 100
      ARCHEAN_parts.Connector: 4
      ARCHEAN_celestial.Aluminium: 300000
      ARCHEAN_celestial.Titanium: 100000
    output:
      ARCHEAN_thruster.BigThruster: 1

  - label: FluidPump
    context: crafter
    category: components
    time: 5
    input:
      ARCHEAN_parts.Casing: 1
      ARCHEAN_parts.Connector: 4
      ARCHEAN_parts.Motor: 1
    output:
      ARCHEAN_thruster.FluidPump: 1
  
  - label: SmallTurboPump
    context: crafter
    category: components
    time: 10
    input:
      ARCHEAN_parts.Casing: 1
      ARCHEAN_parts.Screw: 100
      ARCHEAN_parts.Connector: 4
      ARCHEAN_parts.Motor: 1
      ARCHEAN_celestial.Titanium: 25000
    output:
      ARCHEAN_thruster.SmallTurboPump: 1
  
  - label: BigTurboPump
    context: crafter
    category: components
    time: 20
    input:
      ARCHEAN_parts.Casing: 1
      ARCHEAN_parts.Screw: 100
      ARCHEAN_parts.Connector: 4
      ARCHEAN_parts.Motor: 2
      ARCHEAN_celestial.Titanium: 200000
    output:
      ARCHEAN_thruster.BigTurboPump: 1
