components:
  - ARCHEAN_propeller.Propeller
recipes:
  - label: Propeller
    context: crafter
    category: components
    time: 10
    input:
      ARCHEAN_parts.Casing: 1
      ARCHEAN_parts.Screw: 100
      ARCHEAN_parts.Connector: 3
      ARCHEAN_parts.Motor: 1
      ARCHEAN_parts.Disk: 1
      ARCHEAN_celestial.Aluminium: 100
    output:
      ARCHEAN_propeller.Propeller: 1
