items:
  ARCHEAN_beep.Buzzer:
    max_stack: 256

recipes:
  - label: Buzzer
    context: crafter
    category: components
    time: 10
    input:
      ARCHEAN_parts.Casing: 1
      ARCHEAN_parts.Connector: 1
      ARCHEAN_parts.Magnet: 4
      ARCHEAN_parts.Wire: 10
    output:
      ARCHEAN_beep.Buzzer: 1
