items:
  ARCHEAN_rtg.RTG:
    max_stack: 256

recipes:
  - label: RTG
    context: crafter
    category: components
    time: 20
    input:
      ARCHEAN_parts.Casing: 10
      ARCHEAN_parts.Connector: 3
      ARCHEAN_nuclear.PlutoniumPellet: 8
    output:
      ARCHEAN_rtg.RTG: 1
