items:
  ARCHEAN_build.SteelBeam:
    max_stack: 10000

  ARCHEAN_build.ConcreteBlock:
    max_stack: 10000
  ARCHEAN_build.CompositeBlock:
    max_stack: 10000
  ARCHEAN_build.SteelBlock:
    max_stack: 10000
  ARCHEAN_build.AluminiumBlock:
    max_stack: 10000
  ARCHEAN_build.GlassBlock:
    max_stack: 10000
  ARCHEAN_build.LeadBlock:
    max_stack: 256

  ARCHEAN_build.ConstructorTool:
    max_stack: 1
  ARCHEAN_build.DestructorTool:
    max_stack: 1
  ARCHEAN_build.BlueprintTool:
    max_stack: 1
  ARCHEAN_build.PaintTool:
    max_stack: 1
  ARCHEAN_build.LabelTool:
    max_stack: 1
  ARCHEAN_build.DashboardTool:
    max_stack: 1

  ARCHEAN_build.DataCable:
    max_stack: 1
  ARCHEAN_build.LowVoltageCable:
    max_stack: 1
  ARCHEAN_build.HighVoltageCable:
    max_stack: 1
  ARCHEAN_build.FluidPipe:
    max_stack: 1
  ARCHEAN_build.ItemConduit:
    max_stack: 1

  ARCHEAN_build.SmallPivot:
    max_stack: 256
  ARCHEAN_build.SmallHinge:
    max_stack: 256
  ARCHEAN_build.DockableDoor:
    max_stack: 8
  ARCHEAN_build.DockingPort:
    max_stack: 64
  ARCHEAN_build.Volume:
    max_stack: 256
  ARCHEAN_build.Hitch:
    max_stack: 64


recipes:

  - label: SteelBeam
    context: crafter
    category: construction
    time: 0.1
    input:
      ARCHEAN_celestial.Iron: 9990
      ARCHEAN_celestial.Carbon: 10
    output:
      ARCHEAN_build.SteelBeam: 1
  
  - label: ConcreteBlock
    context: crafter
    category: construction
    time: 0.1
    input:
      ARCHEAN_celestial.Silicon: 10000
      H2O: 0.005
      O2: 0.001
    output:
      ARCHEAN_build.ConcreteBlock: 1
  
  - label: CompositeBlock
    context: crafter
    category: construction
    time: 0.1
    input:
      ARCHEAN_parts.Plastic: 1
    output:
      ARCHEAN_build.CompositeBlock: 1
  
  - label: SteelBlock
    context: crafter
    category: construction
    time: 0.1
    input:
      ARCHEAN_celestial.Iron: 1000
      ARCHEAN_celestial.Carbon: 1
    output:
      ARCHEAN_build.SteelBlock: 1
  
  - label: AluminiumBlock
    context: crafter
    category: construction
    time: 0.1
    input:
      ARCHEAN_celestial.Aluminium: 500
    output:
      ARCHEAN_build.AluminiumBlock: 1
  
  - label: GlassBlock
    context: crafter
    category: construction
    time: 0.1
    input:
      ARCHEAN_celestial.Silicon: 1000
      O2: 0.001
      H2: 0.001
    output:
      ARCHEAN_build.GlassBlock: 1
  
  - label: LeadBlock
    context: crafter
    category: construction
    time: 1
    input:
      ARCHEAN_celestial.Lead: 150000
    output:
      ARCHEAN_build.LeadBlock: 1

  - label: ConstructorTool
    context: crafter
    category: tools
    time: 10
    input:
      ARCHEAN_celestial.Iron: 1000
      ARCHEAN_parts.Screw: 10
    output:
      ARCHEAN_build.ConstructorTool: 1
    
  - label: DestructorTool
    context: crafter
    category: tools
    time: 10
    input:
      ARCHEAN_celestial.Iron: 1000
    output:
      ARCHEAN_build.DestructorTool: 1
  
  - label: BlueprintTool
    context: crafter
    category: tools
    time: 10
    input:
      ARCHEAN_celestial.Iron: 1000
      ARCHEAN_parts.Screw: 10
      ARCHEAN_parts.Circuit: 1
    output:
      ARCHEAN_build.BlueprintTool: 1
    
  - label: PaintTool
    context: crafter
    category: tools
    time: 10
    input:
      ARCHEAN_celestial.Iron: 1000
      ARCHEAN_parts.Screw: 10
    output:
      ARCHEAN_build.PaintTool: 1
    
  - label: LabelTool
    context: crafter
    category: tools
    time: 10
    input:
      ARCHEAN_celestial.Iron: 1000
      ARCHEAN_parts.Screw: 10
    output:
      ARCHEAN_build.LabelTool: 1
    
  - label: DashboardTool
    context: crafter
    category: tools
    time: 10
    input:
      ARCHEAN_celestial.Iron: 1000
      ARCHEAN_parts.Screw: 10
      ARCHEAN_parts.LED: 10
      ARCHEAN_parts.Circuit: 1
    output:
      ARCHEAN_build.DashboardTool: 1

  - label: DataCable
    context: crafter
    category: spools
    time: 10
    input:
      ARCHEAN_parts.Wire: 100
      ARCHEAN_parts.Connector: 10
    output:
      ARCHEAN_build.DataCable: 1
  
  - label: LowVoltageCable
    context: crafter
    category: spools
    time: 10
    input:
      ARCHEAN_parts.Wire: 100
      ARCHEAN_parts.Connector: 10
    output:
      ARCHEAN_build.LowVoltageCable: 1
  
  - label: HighVoltageCable
    context: crafter
    category: spools
    time: 10
    input:
      ARCHEAN_parts.Wire: 200
      ARCHEAN_parts.Connector: 10
    output:
      ARCHEAN_build.HighVoltageCable: 1
  
  - label: FluidPipe
    context: crafter
    category: spools
    time: 10
    input:
      ARCHEAN_celestial.Iron: 100
      ARCHEAN_parts.Connector: 10
    output:
      ARCHEAN_build.FluidPipe: 1
  
  - label: ItemConduit
    context: crafter
    category: spools
    time: 10
    input:
      ARCHEAN_celestial.Iron: 100
      ARCHEAN_parts.Connector: 10
    output:
      ARCHEAN_build.ItemConduit: 1
  
  - label: SmallPivot
    context: crafter
    category: components
    time: 5
    input:
      ARCHEAN_parts.Casing: 1
      ARCHEAN_parts.Screw: 10
      ARCHEAN_parts.Connector: 2
      ARCHEAN_parts.Motor: 1
    output:
      ARCHEAN_build.SmallPivot: 1
  
  - label: SmallHinge
    context: crafter
    category: components
    time: 5
    input:
      ARCHEAN_parts.Casing: 1
      ARCHEAN_parts.Screw: 10
      ARCHEAN_parts.Connector: 2
      ARCHEAN_parts.Motor: 1
    output:
      ARCHEAN_build.SmallHinge: 1
  
  - label: DockingPort
    context: crafter
    category: components
    time: 10
    input:
      ARCHEAN_parts.Casing: 40
      ARCHEAN_parts.Screw: 10
      ARCHEAN_parts.Connector: 5
      ARCHEAN_parts.Magnet: 10
    output:
      ARCHEAN_build.DockingPort: 1
    
  - label: DockableDoor
    context: crafter
    category: components
    time: 30
    input:
      ARCHEAN_parts.Casing: 240
      ARCHEAN_parts.Screw: 100
      ARCHEAN_parts.Connector: 6
      ARCHEAN_parts.Motor: 2
      ARCHEAN_parts.Circuit: 1
      ARCHEAN_parts.LED: 10
      ARCHEAN_build.DockingPort: 2
      ARCHEAN_build.SmallHinge: 4
    output:
      ARCHEAN_build.DockableDoor: 1

  - label: Volume
    context: crafter
    category: components
    time: 10
    input:
      ARCHEAN_parts.Circuit: 1
      ARCHEAN_parts.Panel: 1
      ARCHEAN_parts.LED: 10
    output:
      ARCHEAN_build.Volume: 1
    
  - label: Hitch
    context: crafter
    category: components
    time: 10
    input:
      ARCHEAN_parts.Casing: 40
      ARCHEAN_parts.Screw: 10
      ARCHEAN_parts.Connector: 1
      ARCHEAN_parts.Magnet: 10
    output:
      ARCHEAN_build.Hitch: 1
    