items:
  ARCHEAN_hud.HudController:
    max_stack: 256

recipes:

  - label: HudController
    context: crafter
    category: components
    time: 1
    input:
      ARCHEAN_parts.Panel: 1
      ARCHEAN_parts.Circuit: 1
      ARCHEAN_parts.Connector: 1
    output:
      ARCHEAN_hud.HudController: 1
