items:
  ARCHEAN_computer.Computer:
    max_stack: 256
  ARCHEAN_computer.MiniComputer:
    max_stack: 256
  ARCHEAN_computer.Router:
    max_stack: 256
  ARCHEAN_computer.MiniRouter:
    max_stack: 256

  ARCHEAN_computer.HDD:
    max_stack: 256

recipes:

  - label: HDD
    context: crafter
    category: parts
    time: 10
    input:
      ARCHEAN_parts.Circuit: 1
      ARCHEAN_parts.Disk: 1
    output:
      ARCHEAN_computer.HDD: 1
  
  - label: Computer
    context: crafter
    category: components
    time: 30
    input:
      ARCHEAN_parts.Circuit: 1
      ARCHEAN_parts.Casing: 5
      ARCHEAN_parts.Panel: 5
      ARCHEAN_parts.Screw: 100
      ARCHEAN_parts.Wire: 10
      ARCHEAN_parts.LED: 100
      ARCHEAN_parts.Connector: 13
    output:
      ARCHEAN_computer.Computer: 1
  
  - label: MiniComputer
    context: crafter
    category: components
    time: 20
    input:
      ARCHEAN_parts.Circuit: 1
      ARCHEAN_parts.Casing: 5
      ARCHEAN_parts.Screw: 100
      ARCHEAN_parts.Wire: 10
      ARCHEAN_parts.LED: 1
      ARCHEAN_parts.Connector: 13
    output:
      ARCHEAN_computer.MiniComputer: 1
  
  - label: Router
    context: crafter
    category: components
    time: 20
    input:
      ARCHEAN_parts.Circuit: 1
      ARCHEAN_parts.Casing: 20
      ARCHEAN_parts.Connector: 31
    output:
      ARCHEAN_computer.Router: 1

  - label: MiniRouter
    context: crafter
    category: components
    time: 10
    input:
      ARCHEAN_parts.Circuit: 1
      ARCHEAN_parts.Casing: 5
      ARCHEAN_parts.Connector: 15
    output:
      ARCHEAN_computer.MiniRouter: 1
