components:
  - ARCHEAN_machines.Crusher

recipes:

  - label: Crusher
    context: avatar
    category: components
    time: 60
    input:
      ARCHEAN_parts.Casing: 2
      ARCHEAN_parts.Disk: 2
      ARCHEAN_parts.Motor: 1
      ARCHEAN_parts.Screw: 100
      ARCHEAN_parts.Connector: 4
      ARCHEAN_celestial.Tungsten: 10
      ARCHEAN_celestial.Lead: 1
    output:
      ARCHEAN_machines.Crusher: 1
