components:
  - ARCHEAN_hid.PushButton
  - ARCHEAN_hid.ToggleButton
  - ARCHEAN_hid.ThrottleLever

recipes:

  - label: PushButton
    context: avatar
    category: components
    time: 1
    input:
      ARCHEAN_parts.Casing: 1
      ARCHEAN_parts.Screw: 1
      ARCHEAN_parts.Wire: 1
      ARCHEAN_parts.LED: 1
      ARCHEAN_parts.Connector: 1
    output:
      ARCHEAN_hid.PushButton: 1
  
  - label: ToggleButton
    context: avatar
    category: components
    time: 1
    input:
      ARCHEAN_parts.Casing: 1
      ARCHEAN_parts.Screw: 1
      ARCHEAN_parts.Wire: 1
      ARCHEAN_parts.Connector: 1
    output:
      ARCHEAN_hid.ToggleButton: 1
  
  - label: ThrottleLever
    context: avatar
    category: components
    time: 1
    input:
      ARCHEAN_parts.Casing: 2
      ARCHEAN_parts.Screw: 10
      ARCHEAN_parts.Wire: 1
      ARCHEAN_parts.Connector: 1
    output:
      ARCHEAN_hid.ThrottleLever: 1
