items:
  ARCHEAN_storage.TrashCan:
    max_stack: 256
  ARCHEAN_storage.Container:
    max_stack: 64
  ARCHEAN_storage.SmallContainer:
    max_stack: 64

recipes:

  - label: TrashCan
    context: crafter
    category: components
    time: 1
    input:
      ARCHEAN_parts.Casing: 10
    output:
      ARCHEAN_storage.TrashCan: 1
  
  - label: Container
    context: crafter
    category: components
    time: 10
    input:
      ARCHEAN_parts.Casing: 100
      ARCHEAN_parts.Connector: 3
    output:
      ARCHEAN_storage.Container: 1

  - label: SmallContainer
    context: crafter
    category: components
    time: 5
    input:
      ARCHEAN_parts.Casing: 50
      ARCHEAN_parts.Connector: 3
    output:
      ARCHEAN_storage.SmallContainer: 1
