components:
  - ARCHEAN_gyroscope.SmallGyroscope
  - ARCHEAN_gyroscope.Gyroscope

recipes:
  
  - label: SmallGyroscope
    context: crafter
    category: components
    time: 5
    input:
      ARCHEAN_parts.Casing: 1
      ARCHEAN_parts.Screw: 100
      ARCHEAN_parts.Connector: 2
      ARCHEAN_parts.Magnet: 2
      ARCHEAN_parts.Motor: 2
      ARCHEAN_parts.Disk: 2
      ARCHEAN_celestial.Lead: 2
    output:
      ARCHEAN_gyroscope.SmallGyroscope: 1
  
  - label: Gyroscope
    context: crafter
    category: components
    time: 10
    input:
      ARCHEAN_parts.Casing: 1
      ARCHEAN_parts.Screw: 100
      ARCHEAN_parts.Connector: 2
      ARCHEAN_parts.Magnet: 2
      ARCHEAN_parts.Motor: 2
      ARCHEAN_parts.Disk: 10
      ARCHEAN_celestial.Lead: 10
    output:
      ARCHEAN_gyroscope.Gyroscope: 1
